### PR TITLE
Change the way to get the last_quote

### PR DESCRIPTION
**Pull request by pbrissaud**
Using ticker it should resolve some issues (#92) : 

```python
ticker_info = ticker.info
history = ticker.history()
last_quote = (history.tail(1)['Close'].iloc[0])
```

### CODE REVIEW

**Comment by pbrissaud** [comment]
Hi @vutsalsinghal,
Can you test with this fix ? You can use the `docker-compose.dev.yaml` file to build the image from this branch.

**Comment by vutsalsinghal** [comment]
@pbrissaud  thanks for quick response. I tested it and it works but something else fails...

```
KeyError: 'sector' on line 110
```

it can be suppressed using 

```
info_values = label_values + [ticker_info['currency'], ticker_info['exchange'],
                                              ticker_info['logo_url'], ticker_info['market'], ticker_info.get('sector',"")]
```
The default vault for sector - ""

With the above change, it seems to be working fine.

**Comment by vutsalsinghal** [comment]
Weird thing is, BTC-USD is getting pushed to prometheus but doesnt show up on grafana

image

**Comment by pbrissaud** [comment]
Hi @vutsalsinghal , 

Using your fix, I set the default value "undefined" for all share infos. Using this, I see well the Bitcoin in Grafana. 

Can you test if it's good for you ?

**Comment by vutsalsinghal** [comment]
Its working now! Thank you.

**Pull request merged**
